version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_env03
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    extra_hosts:
      - "localhost: 10.10.2.71"
    networks:
      - app-network
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_env03
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     # KAFKA_CREATE_TOPICS: testtopic:1:1
     # KAFKA_LISTENERS: INTERNAL://kafka:29092,OUTSIDE://127.0.0.1:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,OUTSIDE://192.168.0.100:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "localhost: 10.10.2.71"
    networks:
      - app-network

  kafkaUI:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_UI03
    ports:
      - 8082:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    extra_hosts:
      - "localhost: 10.10.2.71"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  default:
    driver: bridge
